version: "3.9"

services:
  frontend:
    # change build folder to ./frontend in final merge with our backend boy
    build: ./
    container_name: frontend_c
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
